Dreamscape Symphony: dream_analysis.DreamAnalyzer Class Reference
dream_analysis.DreamAnalyzer Class Reference
Public Member Functions
def __init__ (self)
List[str] extract_named_entity (self, str text)
Tuple[str, float] analyze_sentiment (self, str text)
List[str] extract_keywords (self, List[str] text, int num_keywords=10)
def get_themes (self, List[str] text)
Tuple[List[str], Tuple[str, float], List[str], List[List[str]]] analyze_dream (self, str text)
def __init__ (self)
List[str] extract_named_entity (self, str text)
Tuple[str, float] analyze_sentiment (self, str text)
List[str] extract_keywords (self, List[str] text, int num_keywords=10)
def get_themes (self, List[str] text)
Tuple[List[str], Tuple[str, float], List[str], List[List[str]]] analyze_dream (self, str text)
Public Attributes
ner_pipeline
sentiment_pipeline
vectorizer
Detailed Description
A class for analyzing dreams and extracting relevant information.
Attributes:
    ner_pipeline (pipeline): A pipeline for named entity recognition using the BERT model.
    sentiment_pipeline (pipeline): A pipeline for sentiment analysis using the DistilBERT model.
    vectorizer (TfidfVectorizer): A vectorizer for text data using TF-IDF.
Methods:
    __init__(self): Initializes the DreamAnalyzer class.
    extract_named_entity(self, text: str) -> List[str]: Extracts named entities from the given text.
    analyze_sentiment(self, text: str) -> Tuple[str, float]: Analyzes the sentiment of the given text and returns the emotion and score.
    extract_keywords(self, text: List[str], num_keywords: int = 10) -> List[str]: Extracts the top keywords from the given text.
    get_themes(self, text: List[str]) -> List[List[str]]: Identifies the main themes in the given text using NMF.
    analyze_dream(
        self, text: str
    ) -> Tuple[List[str], Tuple[str, float], List[str], List[List[str]]]: Analyzes a dream by extracting named entities, sentiment, keywords, and themes.
Definition at line 14 of file gh-pages/modules/dream_analysis/dream_analysis.py.
Constructor & Destructor Documentation
__init__() [1/2]
def dream_analysis.DreamAnalyzer.__init__ (self)
Initialize the DreamAnalyzer class.
:return: None
Definition at line 34 of file gh-pages/modules/dream_analysis/dream_analysis.py.
     def __init__(self):
         """
         Initialize the DreamAnalyzer class.
         :return: None
         """
         self.ner_pipeline = pipeline(
             model="dbmdz/bert-large-cased-finetuned-conll03-english",
             grouped_entities=True,
         )
         self.sentiment_pipeline = pipeline(
             model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
         )
         self.vectorizer = TfidfVectorizer(stop_words="english", max_features=5000)
Referenced by dream_analysis.DreamAnalyzer.__init__().
__init__() [2/2]
def dream_analysis.DreamAnalyzer.__init__ (self)
Initialize the DreamAnalyzer class.
:return: None
Definition at line 34 of file modules/dream_analysis/dream_analysis.py.
     def __init__(self):
         """
         Initialize the DreamAnalyzer class.
         :return: None
         """
         self.ner_pipeline = pipeline(
             model="dbmdz/bert-large-cased-finetuned-conll03-english",
             grouped_entities=True,
         )
         self.sentiment_pipeline = pipeline(
             model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
         )
         self.vectorizer = TfidfVectorizer(stop_words="english", max_features=5000)
References dream_analysis.DreamAnalyzer.__init__(), dream_analysis.DreamAnalyzer.ner_pipeline, dream_analysis.DreamAnalyzer.sentiment_pipeline, and dream_analysis.DreamAnalyzer.vectorizer.
Member Function Documentation
analyze_dream() [1/2]
Tuple[List[str], Tuple[str, float], List[str], List[List[str]]] dream_analysis.DreamAnalyzer.analyze_dream (self, str text)
Extracts named entities from the given text.
:param text: The input text.
:type text: str
:return: A list of unique named entities found in the text.
:rtype: List[str]
Definition at line 120 of file gh-pages/modules/dream_analysis/dream_analysis.py.
     ) -> Tuple[List[str], Tuple[str, float], List[str], List[List[str]]]:
         """
         Extracts named entities from the given text.
         :param text: The input text.
         :type text: str
         :return: A list of unique named entities found in the text.
         :rtype: List[str]
         """
         named_entity = self.extract_named_entity(text)
         sentiment = self.analyze_sentiment(text)
         document = sent_tokenize(text)
         keywords = self.extract_keywords(document)
         themes = self.get_themes(document)
         return named_entity, sentiment, keywords, list(themes)
References dream_analysis.DreamAnalyzer.analyze_sentiment(), dream_analysis.DreamAnalyzer.extract_keywords(), dream_analysis.DreamAnalyzer.extract_named_entity(), and dream_analysis.DreamAnalyzer.get_themes().
Referenced by dream_analysis.DreamAnalyzer.analyze_dream().
analyze_dream() [2/2]
Tuple[List[str], Tuple[str, float], List[str], List[List[str]]] dream_analysis.DreamAnalyzer.analyze_dream (self, str text)
Extracts named entities from the given text.
:param text: The input text.
:type text: str
:return: A list of unique named entities found in the text.
:rtype: List[str]
Definition at line 120 of file modules/dream_analysis/dream_analysis.py.
     ) -> Tuple[List[str], Tuple[str, float], List[str], List[List[str]]]:
         """
         Extracts named entities from the given text.
         :param text: The input text.
         :type text: str
         :return: A list of unique named entities found in the text.
         :rtype: List[str]
         """
         named_entity = self.extract_named_entity(text)
         sentiment = self.analyze_sentiment(text)
         document = sent_tokenize(text)
         keywords = self.extract_keywords(document)
         themes = self.get_themes(document)
         return named_entity, sentiment, keywords, list(themes)
References dream_analysis.DreamAnalyzer.analyze_dream(), dream_analysis.DreamAnalyzer.analyze_sentiment(), dream_analysis.DreamAnalyzer.extract_keywords(), dream_analysis.DreamAnalyzer.extract_named_entity(), and dream_analysis.DreamAnalyzer.get_themes().
analyze_sentiment() [1/2]
Tuple[str, float] dream_analysis.DreamAnalyzer.analyze_sentiment (self, str text)
Extracts named entities from the given text.
:param text: The input text.
:type text: str
:return: A list of unique named entities found in the text.
:rtype: List[str]
Definition at line 64 of file gh-pages/modules/dream_analysis/dream_analysis.py.
     def analyze_sentiment(self, text: str) -> Tuple[str, float]:
         """
         Extracts named entities from the given text.
         :param text: The input text.
         :type text: str
         :return: A list of unique named entities found in the text.
         :rtype: List[str]
         """
         sentiment = self.sentiment_pipeline(text)[0]
         emotion = sentiment["label"]
         score = sentiment["score"]
         return emotion, score
References dream_analysis.DreamAnalyzer.sentiment_pipeline.
Referenced by dream_analysis.DreamAnalyzer.analyze_dream(), and dream_analysis.DreamAnalyzer.analyze_sentiment().
analyze_sentiment() [2/2]
Tuple[str, float] dream_analysis.DreamAnalyzer.analyze_sentiment (self, str text)
Extracts named entities from the given text.
:param text: The input text.
:type text: str
:return: A list of unique named entities found in the text.
:rtype: List[str]
Definition at line 64 of file modules/dream_analysis/dream_analysis.py.
     def analyze_sentiment(self, text: str) -> Tuple[str, float]:
         """
         Extracts named entities from the given text.
         :param text: The input text.
         :type text: str
         :return: A list of unique named entities found in the text.
         :rtype: List[str]
         """
         sentiment = self.sentiment_pipeline(text)[0]
         emotion = sentiment["label"]
         score = sentiment["score"]
         return emotion, score
References dream_analysis.DreamAnalyzer.analyze_sentiment(), and dream_analysis.DreamAnalyzer.sentiment_pipeline.
Referenced by dream_analysis.DreamAnalyzer.analyze_dream().
extract_keywords() [1/2]
List[str] dream_analysis.DreamAnalyzer.extract_keywords (self, List[str] text, int num_keywords = 10)
Extracts named entities from the given text.
:param text: The input text.
:type text: str
:return: A list of unique named entities found in the text.
:rtype: List[str]
Definition at line 79 of file gh-pages/modules/dream_analysis/dream_analysis.py.
     def extract_keywords(self, text: List[str], num_keywords: int = 10) -> List[str]:
         """
         Extracts named entities from the given text.
         :param text: The input text.
         :type text: str
         :return: A list of unique named entities found in the text.
         :rtype: List[str]
         """
         tfidf_matrix = self.vectorizer.fit_transform(text)
         feature_names = self.vectorizer.get_feature_names_out()
         scores = np.asarray(tfidf_matrix.sum(axis=0)).ravel()
         feature_names = self.vectorizer.get_feature_names_out()
         keyword_scores = dict(zip(feature_names, scores))
         sorted_keywords = sorted(
             keyword_scores.items(), key=lambda x: x[1], reverse=True
         )
         top_keywords = [keyword for keyword, score in sorted_keywords[:num_keywords]]
         return top_keywords
References dream_analysis.DreamAnalyzer.vectorizer.
Referenced by dream_analysis.DreamAnalyzer.analyze_dream(), and dream_analysis.DreamAnalyzer.extract_keywords().
extract_keywords() [2/2]
List[str] dream_analysis.DreamAnalyzer.extract_keywords (self, List[str] text, int num_keywords = 10)
Extracts named entities from the given text.
:param text: The input text.
:type text: str
:return: A list of unique named entities found in the text.
:rtype: List[str]
Definition at line 79 of file modules/dream_analysis/dream_analysis.py.
     def extract_keywords(self, text: List[str], num_keywords: int = 10) -> List[str]:
         """
         Extracts named entities from the given text.
         :param text: The input text.
         :type text: str
         :return: A list of unique named entities found in the text.
         :rtype: List[str]
         """
         tfidf_matrix = self.vectorizer.fit_transform(text)
         feature_names = self.vectorizer.get_feature_names_out()
         scores = np.asarray(tfidf_matrix.sum(axis=0)).ravel()
         feature_names = self.vectorizer.get_feature_names_out()
         keyword_scores = dict(zip(feature_names, scores))
         sorted_keywords = sorted(
             keyword_scores.items(), key=lambda x: x[1], reverse=True
         )
         top_keywords = [keyword for keyword, score in sorted_keywords[:num_keywords]]
         return top_keywords
References dream_analysis.DreamAnalyzer.extract_keywords(), and dream_analysis.DreamAnalyzer.vectorizer.
Referenced by dream_analysis.DreamAnalyzer.analyze_dream().
extract_named_entity() [1/2]
List[str] dream_analysis.DreamAnalyzer.extract_named_entity (self, str text)
Extracts named entities from the given text.
:param text: The input text.
:type text: str
:return: A list of unique named entities found in the text.
:rtype: List[str]
Definition at line 49 of file gh-pages/modules/dream_analysis/dream_analysis.py.
     def extract_named_entity(self, text: str) -> List[str]:
         """
         Extracts named entities from the given text.
         :param text: The input text.
         :type text: str
         :return: A list of unique named entities found in the text.
         :rtype: List[str]
         """
         entities = self.ner_pipeline(text)
         themes = [entity["word"] for entity in entities]
         unique_themes = list(set(themes))
         return unique_themes
References dream_analysis.DreamAnalyzer.ner_pipeline.
Referenced by dream_analysis.DreamAnalyzer.analyze_dream(), and dream_analysis.DreamAnalyzer.extract_named_entity().
extract_named_entity() [2/2]
List[str] dream_analysis.DreamAnalyzer.extract_named_entity (self, str text)
Extracts named entities from the given text.
:param text: The input text.
:type text: str
:return: A list of unique named entities found in the text.
:rtype: List[str]
Definition at line 49 of file modules/dream_analysis/dream_analysis.py.
     def extract_named_entity(self, text: str) -> List[str]:
         """
         Extracts named entities from the given text.
         :param text: The input text.
         :type text: str
         :return: A list of unique named entities found in the text.
         :rtype: List[str]
         """
         entities = self.ner_pipeline(text)
         themes = [entity["word"] for entity in entities]
         unique_themes = list(set(themes))
         return unique_themes
References dream_analysis.DreamAnalyzer.extract_named_entity(), and dream_analysis.DreamAnalyzer.ner_pipeline.
Referenced by dream_analysis.DreamAnalyzer.analyze_dream().
get_themes() [1/2]
def dream_analysis.DreamAnalyzer.get_themes (self, List[str] text)
Extracts named entities from the given text.
:param text: The input text.
:type text: str
:return: A list of unique named entities found in the text.
:rtype: List[str]
Definition at line 100 of file gh-pages/modules/dream_analysis/dream_analysis.py.
     def get_themes(self, text: List[str]):
         """
         Extracts named entities from the given text.
         :param text: The input text.
         :type text: str
         :return: A list of unique named entities found in the text.
         :rtype: List[str]
         """
         tfidf_matrix = self.vectorizer.fit_transform(text)
         num_topics = 2
         nmf_model = NMF(n_components=num_topics, init="random", random_state=42)
         nmf_matrix = nmf_model.fit_transform(tfidf_matrix)
         feature_names = np.array(self.vectorizer.get_feature_names_out())
         top_feature_indices = np.argsort(nmf_model.components_, axis=1)[:, :-11:-1]
         top_features = [list(feature) for feature in feature_names[top_feature_indices]]
         return top_features
References dream_analysis.DreamAnalyzer.vectorizer.
Referenced by dream_analysis.DreamAnalyzer.analyze_dream(), and dream_analysis.DreamAnalyzer.get_themes().
get_themes() [2/2]
def dream_analysis.DreamAnalyzer.get_themes (self, List[str] text)
Extracts named entities from the given text.
:param text: The input text.
:type text: str
:return: A list of unique named entities found in the text.
:rtype: List[str]
Definition at line 100 of file modules/dream_analysis/dream_analysis.py.
     def get_themes(self, text: List[str]):
         """
         Extracts named entities from the given text.
         :param text: The input text.
         :type text: str
         :return: A list of unique named entities found in the text.
         :rtype: List[str]
         """
         tfidf_matrix = self.vectorizer.fit_transform(text)
         num_topics = 2
         nmf_model = NMF(n_components=num_topics, init="random", random_state=42)
         nmf_matrix = nmf_model.fit_transform(tfidf_matrix)
         feature_names = np.array(self.vectorizer.get_feature_names_out())
         top_feature_indices = np.argsort(nmf_model.components_, axis=1)[:, :-11:-1]
         top_features = [list(feature) for feature in feature_names[top_feature_indices]]
         return top_features
References dream_analysis.DreamAnalyzer.get_themes(), and dream_analysis.DreamAnalyzer.vectorizer.
Referenced by dream_analysis.DreamAnalyzer.analyze_dream().
Member Data Documentation
ner_pipeline
dream_analysis.DreamAnalyzer.ner_pipeline
Definition at line 40 of file gh-pages/modules/dream_analysis/dream_analysis.py.
Referenced by dream_analysis.DreamAnalyzer.__init__(), and dream_analysis.DreamAnalyzer.extract_named_entity().
sentiment_pipeline
dream_analysis.DreamAnalyzer.sentiment_pipeline
Definition at line 44 of file gh-pages/modules/dream_analysis/dream_analysis.py.
Referenced by dream_analysis.DreamAnalyzer.__init__(), and dream_analysis.DreamAnalyzer.analyze_sentiment().
vectorizer
dream_analysis.DreamAnalyzer.vectorizer
Definition at line 47 of file gh-pages/modules/dream_analysis/dream_analysis.py.
Referenced by dream_analysis.DreamAnalyzer.__init__(), dream_analysis.DreamAnalyzer.extract_keywords(), and dream_analysis.DreamAnalyzer.get_themes().
The documentation for this class was generated from the following file:
gh-pages/modules/dream_analysis/dream_analysis.py