[theme]
primaryColor="#FF4F79"
backgroundColor="#E9D3D0"
secondaryBackgroundColor="#80FFE8"
textColor="#363946"
font="sans serif"

[theme.dark]
primaryColor="#FF4F79"
backgroundColor="#363946"
secondaryBackgroundColor="#70A9A1"
textColor="#E9D3D0"
font="sans serif"